version: '3'
services:
  frontend:
    build: ./  # Path to your Angular app
    ports:
      - "80:80"  # Map Angular app to port 80 on the host

  backend:
    build: ./backend  # Path to your backend folder
    ports:
      - "4000:4000"  # Map backend to port 4000
    depends_on:
      - mongo  # Ensure MongoDB starts before the backend

  mongo:
    image: mongo:latest  # Use the latest MongoDB image
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - ./data:/data/db  # Persist MongoDB data in the ./data folder
